# -*- coding: utf-8 -*-

# Make import work like include(./../pkg)
import os, sys
try:
    file = __file__
except:
    file = sys.argv[0]
suffix = '\\..'
path=os.path.dirname(os.path.abspath(__file__)) + suffix
sys.path.insert(0, path)

import MVPBase
# TODO: when binds are registered, have some way to allow the presetner
# to disable them
class Observer(MVPBase.BaseObserver):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
    # called by mvpbase_presenter.start()
    def start(self, *args, **kwargs):
        super().start(*args, **kwargs)
        # now model and presenter are coupled
        
    def callback_register_all(self):
        """ set callbacks for events generated by model """
        presenter = self._observer
